# Generated by Django 4.2.7 on 2026-01-30 09:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarbonFootprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beef_consumption', models.FloatField(default=0, help_text='kg per month')),
                ('chicken_consumption', models.FloatField(default=0, help_text='kg per month')),
                ('fish_consumption', models.FloatField(default=0, help_text='kg per month')),
                ('vegetable_consumption', models.FloatField(default=0, help_text='kg per month')),
                ('natural_gas_usage', models.FloatField(default=0, help_text='cubic meters per month')),
                ('electricity_usage', models.FloatField(default=0, help_text='kWh per month')),
                ('car_miles', models.FloatField(default=0, help_text='miles per month')),
                ('public_transport_miles', models.FloatField(default=0, help_text='miles per month')),
                ('total_food_carbon', models.FloatField(default=0, help_text='kg CO2e per month')),
                ('total_energy_carbon', models.FloatField(default=0, help_text='kg CO2e per month')),
                ('total_carbon', models.FloatField(default=0, help_text='kg CO2e per month')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carbon_footprints', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
