# Generated by Django 4.2.7 on 2026-01-30 09:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('issue_type', models.CharField(choices=[('bug', 'Bug Report'), ('feature', 'Feature Request'), ('performance', 'Performance Issue'), ('ui', 'UI/UX Issue'), ('calculation', 'Calculation Error'), ('other', 'Other')], max_length=20)),
                ('page', models.CharField(choices=[('home', 'Home Page'), ('calculator', 'Calculator'), ('tips', 'Tips Page'), ('about', 'About Page'), ('comparison', 'Community Comparison'), ('login', 'Login/Signup'), ('other', 'Other')], max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('follow_up', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issue_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
